Properties
itmo-is-dev/SourceKit pull request #13
Opened 2023-06-22 04:28 UTC by Walter-Rabbit

2023-06-24 13:40 UTC, ronimizy requested changes
как-то вот так

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +            }
добавь тест на 

```cs
public class PrivateReadonlyField
{
    private readonly string _field;

    public string GetField() => _field;
}
```

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +    public const string Format = """Variable '{0}' could be converted to property.""";
Field

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +    private void FindMethods(
нейминг ниоч, сделай аналогично методу выше

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +            }
```suggestion
            if (getMethods.TryGetValue(variable.Identifier.ToString(), out var getMethod) is false)
            {
                return;
            }
```

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +            var isGetMethod = getMethods.TryGetValue(variable.Identifier.ToString(), out var getMethod);
вынеси в переменную `variable.Identifier.ToString()`, много где используешь

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +            if (isSetMethod && setMethod is not null)
```suggestion
            if (setMethods.TryGetValue(variable.Identifier.ToString(), out var setMethod))
```

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +                variable.Identifier.Text));
```suggestion
            context.ReportDiagnostic(Diagnostic.Create(
                Descriptor, 
                getMethodLocation,
                additionalLocations,
                variable.Identifier.Text));

            context.ReportDiagnostic(Diagnostic.Create(
                Descriptor, 
                variableLocation, 
                additionalLocations,
                variable.Identifier.Text));
```

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +            });
1. оч тяжело читать
2. не всегда надо всё делать через `ChildNodes`, у типизированных нод есть специальные свойства 
3. лучше всё-таки через semantic api делать для точности, чтобы ключом был `IFieldSymbol`, а значением `IMethodSymbol`, а дальше в вызывающем коде получить символ просматриваемого поля, и по нему значение в словаре искать
4. А если кто-то умный сделает два геттер метода?

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +            });
аналогично комментарию выше

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        await Task.WhenAll(declarationCouldBeConvertedToPropertyDiagnostics);
```suggestion
        IEnumerable<Task> diagnostics = context.Diagnostics
            .Where(x => x.Id.Equals(DeclarationCouldBeConvertedToPropertyAnalyzer.DiagnosticId))
            .Select(x => ProvideConvertDeclarationIntoPropertyCodeFix(context, x));

        await Task.WhenAll(diagnostics);
```

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        if (root is null)
```suggestion
        var root = await context.Document.GetSyntaxRootAsync(context.CancellationToken);

        if (root is null)
```

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +            equivalenceKey: nameof(Title),
хм, я в своём коде так делал, но это похоже была ошибка, потому что надо уникальное значение, лучше сделать `nameof` класса с кодфиксом

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +            createChangedDocument: async _ =>
а почему не передаёшь токен?

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        var variableNode = root.FindNode(diagnostic.AdditionalLocations[0].SourceSpan);
почему `AdditionalLocations[0]`

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +            SyntaxFactory.PropertyDeclaration(
`using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;`

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +    }
аллоцируешь лишние строки, есть же `StringBuilder`

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +    }
сделай тест на поле с именем `_field`

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +                        .NormalizeWhitespace())
ты же и так на финальной ноде это вызываешь

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        }
а это в каких случаях происходит?

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        var normalizedRoot = editor.GetChangedRoot().NormalizeWhitespace();
ну, не думаю что стоит прям весь документ нормализовывать, достаточно только кода который ты сгенерил

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +    private static MethodDeclarationSyntax? GetGetterMethodAndDelete(
FindGetterMethodAndDelete

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +    private static MethodDeclarationSyntax? GetGetterMethodAndDelete(
для сеттера аналогично

2023-06-24 13:40 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +
```suggestion
            var setterKind = setterMethod.Modifiers.First().Kind();

            var setterDeclaration = SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken));

```

2023-06-24 13:50 UTC, Walter-Rabbit commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +        fields.ForEach(field =>
Не знал, что он медленней, поэтому хотел всё в linq запихнуть. Окей

2023-06-24 13:53 UTC, Walter-Rabbit commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        var normalizedRoot = editor.GetChangedRoot().NormalizeWhitespace();
Он тогда энтер не ставит после свойства

2023-06-24 13:55 UTC, Walter-Rabbit commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        }
Если чел написал что-то типа
'''cs
public a,b;
'''
То кодфиксер сработает только на то поле, на которое кликнул пользователь. А другое оставит не тронутым.

2023-06-24 13:58 UTC, Walter-Rabbit commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        var variableNode = root.FindNode(diagnostic.AdditionalLocations[0].SourceSpan);
Так как пользователь может кликнуть на метод, а не на переменную, то эту переменную надо найти в коде. Она лежит в метаинформации в массиве дополнительных локаций в [0]. Чтобы не писать несколько вариантов поведения программы для каждой из входных точек (aka location, на которую кликает пользователь), то я просто беру нулевой момент из мета данных, который всегда является переменной.

2023-06-24 14:00 UTC, Walter-Rabbit commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +            });
В теории, анализатор даст по рукам ещё до того, как чел второй метод напишет. А если всё-таки напишет, то я даже не знаю, что в это случае делать, какую защиту от дурака сделать. Поменять только первый метод или не менять вообще?

2023-06-24 14:05 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +        fields.ForEach(field =>
`ForEach` это не линка

2023-06-24 14:06 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +            });
я бы все гетеры убрал, крч меняешь `ToDictionary` на `ToLookup` и делаешь бррр

2023-06-24 14:07 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        var variableNode = root.FindNode(diagnostic.AdditionalLocations[0].SourceSpan);
завязка на индексы не очень нравится, но ладно, пусть будет

2023-06-24 14:09 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        var normalizedRoot = editor.GetChangedRoot().NormalizeWhitespace();
добавь тривию переноса строки. я бы не хотел чтобы когда я применяю кодфикс, у меня менялось форматирование

2023-06-24 15:46 UTC, Walter-Rabbit commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +            equivalenceKey: nameof(Title),
Так?
```cs
var action = CodeAction.Create(
            Title,
            equivalenceKey: nameof(ConvertDeclarationIntoPropertyCodeFixProvider),
            createChangedDocument: async _ =>
            {
                var newDocument = await ReplaceField(root, context, diagnostic);
                return newDocument;
            });
```

2023-06-28 19:30 UTC, ronimizy requested changes
по большей части кодстайл остался

2023-06-28 19:30 UTC, ronimizy commented on src/SourceKit/Extensions/SyntaxTokenListExtensions.cs
> +        }
проверки по строкам очень не люблю)
бахни `// TODO:` на то чтобы в будущем это переделать

2023-06-28 19:30 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        await Task.WhenAll(diagnostics);
```suggestion
        IEnumerable<Task> diagnostics = context.Diagnostics
            .Where(x => x.Id.Equals(DeclarationCouldBeConvertedToPropertyAnalyzer.DiagnosticId))
            .Select(x => ProvideConvertDeclarationIntoPropertyCodeFix(context, x));

        await Task.WhenAll(diagnostics);
```

2023-06-28 19:30 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +    private static async Task<Document> ProcessNotPublicFieldAsync(
nit: в основном используется термин `NonPublic`, не `NotPublic` например в рефлексии `BindingAttributes`, так что лучше неймить согласно общим конвенциям

2023-06-28 19:30 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        }
```suggestion
        var semanticModel = await context.Document.GetSemanticModelAsync(cancellationToken);

        if (semanticModel is null)
        {
            return editor.OriginalDocument;
        }
```

2023-06-28 19:30 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        var variableType = variableDeclaration.Type;
```suggestion
        var editor = await DocumentEditor.CreateAsync(document, cancellationToken);
        var variableType = variableDeclaration.Type;
```

2023-06-28 19:30 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +
```suggestion
        var classDeclarationNode = root.FindNode(diagnostic.AdditionalLocations[1].SourceSpan);

        if (classDeclarationNode is not ClassDeclarationSyntax classDeclaration)
        {
            return editor.OriginalDocument;
        }

```

2023-06-28 19:30 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +
```suggestion
        var getMethod = FindMostAccessibleGetMethod(fieldWithMethods);
        var setMethod = FindMostAccessibleSetMethod(fieldWithMethods);

        DeleteAllMethods(fieldWithMethods, editor);

```

2023-06-28 19:30 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +                .WithModifiers(propertyAccessor);
вынеси получение идентификатора в переменную, оставь вызов `PropertyDeclaration` на той же строке что и объявление переменной

2023-06-28 19:30 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +        {
```suggestion
        var higherAccessor = Accessibility.Private;
        MethodDeclarationSyntax? higherAccessorMethod = null;

        foreach (var getMethod in fieldWithMethods.GetMethods)
        {
```

2023-06-28 19:30 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Properties/CodeFixes/ConvertDeclarationIntoPropertyCodeFixProvider.cs
> +            higherAccessorMethod = getMethod;
```suggestion
            var accessibility = getMethod.Modifiers.ToSyntaxTokenList();

            if (higherAccessor >= accessibility) 
                continue;

            higherAccessor = accessibility;
            higherAccessorMethod = getMethod;
```

2023-06-29 23:20 UTC, Walter-Rabbit commented on src/analyzers/SourceKit.Analyzers.Properties/Analyzers/DeclarationCouldBeConvertedToPropertyAnalyzer.cs
> +                    field.Modifiers.Any(modifier => modifier.Kind() is SyntaxKind.ReadOnlyKeyword))
Я хочу выдавать warning только в тех случаях, когда поле либо без модификаторов, либо только с модификатором readonly. Просто мне кажется странным, если анализатор будет предлагать переделать const переменную в авто-свойство с get;

2023-06-29 23:43 UTC, Walter-Rabbit commented on src/analyzers/SourceKit.Analyzers.Properties/General/NameProducer.cs
> +        }
Поискать нюгет, который уже это делает?)

2023-06-29 23:46 UTC, Walter-Rabbit commented on src/analyzers/SourceKit.Analyzers.Properties/General/NameProducer.cs
> +        }
Нашёл
![image](https://github.com/itmo-is-dev/SourceKit/assets/60439555/f6d39cb3-76bd-4b5f-9808-44df518595be)

2023-07-04 17:44 UTC, Walter-Rabbit commented
Добавил поддержку того, что если чел задал значение по умолчанию, то после генерации авто-свойства это значение сохраняется (тест тоже добавил на это).

```cs
   public string field = 10;
```
Превратится в


```cs
   public string Field { get; set; } = 10;
```

2023-07-04 19:23 UTC, Walter-Rabbit commented
Переделал сравнение модификатор доступа, чтобы не сравнивать строки.
```cs
public static Accessibility ToAccessibility(this SyntaxTokenList syntaxTokenList)
    {
        return syntaxTokenList.Select(t => t.Kind()).ToList() switch
        {
            [SyntaxKind.PrivateKeyword] => Accessibility.Private,
            [SyntaxKind.ProtectedKeyword, SyntaxKind.InternalKeyword] => Accessibility.ProtectedAndInternal,
            [SyntaxKind.ProtectedKeyword] => Accessibility.Protected,
            [SyntaxKind.InternalKeyword] => Accessibility.Internal,
            [SyntaxKind.PublicKeyword] => Accessibility.Public,
            _ => Accessibility.NotApplicable
        };
    }
```

Единственное, мб я бы как-то разделил switch на сравнение, когда модификатор только 1, чтобы не делать массивы из модификаторов каждый раз. Типо if, где проверяется количество модификаторов в SyntaxTokenList. Если 1, то сделать switch просто по одному модификатору. Если 2, то в таком случае делать switch по массиву. 

¯\\_(ツ)_/¯

2023-09-02 12:49 UTC, merged