Feat/remove terminal operation analyzer
itmo-is-dev/SourceKit pull request #14
Opened 2023-06-22 09:55 UTC by MGSDS

2023-06-24 14:04 UTC, ronimizy requested changes

2023-06-24 14:04 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Enumerable/CodeFixes/RemoveTerminalOperationCodeFixProvider.cs
> +
хм, а давай немного упростим тебе задачу. переделаем анализатор на `DoNotEnumerateCollectionInLinqChain`. и диагностику будем репортить на сам терминальный метод.

2023-06-24 14:06 UTC, MGSDS commented on src/analyzers/SourceKit.Analyzers.Enumerable/Helpers/CannotLinqChainAfterTerminalOperationHelper.cs
> +    }
ОЙ.... Я думал что это убрал...

2023-06-25 22:12 UTC, MGSDS commented
@ronimizy не слишком ли я много использую var? Не помню как в шарпе принято

2023-06-26 07:55 UTC, ronimizy commented
> @ronimizy не слишком ли я много использую var? Не помню как в шарпе принято

в райдере есть настройка 
<img width="750" alt="Screenshot 2023-06-26 at 10 55 09" src="https://github.com/itmo-is-dev/SourceKit/assets/71693183/895d3d71-ebfe-45dc-8ba5-7866265ec931">

2023-06-26 08:29 UTC, MGSDS commented
> можешь поставить временно Error у себя, вместо Hint чтобы увидеть)
Спасибо, все пофиксил

2023-06-26 09:19 UTC, ronimizy requested changes
а что у тебя за такой хитрый location для диагностики?

2023-06-26 09:19 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Enumerable/Analyzers/DoNotEnumerateCollectionInLinqChain.cs
> +        if (!hasLinqAncestor) return;
```suggestion
        if (hasLinqAncestor is false) return;
```

2023-06-26 09:19 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Enumerable/CodeFixes/RemoveTerminalOperationCodeFixProvider.cs
> +            , diagnostic);
вынеси CodeAction в отдельную переменную

2023-06-26 09:19 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Enumerable/CodeFixes/RemoveTerminalOperationCodeFixProvider.cs
> +    private static async Task<Solution> RemoveToList(Document document, SyntaxNode node, CancellationToken ctx)
назови токен нормально

2023-06-26 09:24 UTC, MGSDS commented on src/analyzers/SourceKit.Analyzers.Enumerable/Analyzers/DoNotEnumerateCollectionInLinqChain.cs
> +        var symbol = GetSymbol(syntax, model) ?? throw new InvalidOperationException();
Эмм, я это из кода удалил давно...
и оно у тебя сразу же outdated

2023-06-26 09:26 UTC, MGSDS commented on src/analyzers/SourceKit.Analyzers.Enumerable/Analyzers/DoNotEnumerateCollectionInLinqChain.cs
> +    private static bool IsLinqEnumerable(ISymbol? symbol, SemanticModel? model)
Аналогично, в коде этого нет

2023-06-26 10:04 UTC, MGSDS commented
> а что у тебя за такой хитрый location для диагностики?

последний токен в Invocation Expression, тоесть сам вызов метода без (), например в GetItems().ToLookup(x => x, new Comparer<int>()).First() location будет указывать на ToLookup

2023-06-26 10:26 UTC, ronimizy commented
> > а что у тебя за такой хитрый location для диагностики?
> 
> последний токен в MemberAccessExpressionSyntax, а именно сам вызов метода без (), например в GetItems().ToLookup(x => x, new Comparer()).First() location будет указывать на ToLookup

ну смотри, просто кажется тебе будет сильно проще кодфикс делать, если ты будешь просто на весь MemberAccessExpressionSyntax диагностику кидать)

2023-06-26 10:29 UTC, MGSDS commented
> > > а что у тебя за такой хитрый location для диагностики?
> > 
> > 
> > последний токен в MemberAccessExpressionSyntax, а именно сам вызов метода без (), например в GetItems().ToLookup(x => x, new Comparer()).First() location будет указывать на ToLookup
> 
> ну смотри, просто кажется тебе будет сильно проще кодфикс делать, если ты будешь просто на весь MemberAccessExpressionSyntax диагностику кидать)

У меня же когда warning будет кидаться на GetItems().ToLookup(x => x, new Comparer()) в том примере. Звучит как-то не очень, как мне кажестя, но если тебя это устроит могу и так сделать

2023-06-26 10:32 UTC, MGSDS commented
> в идеале чтобы она кидалась только на `.ToLookup(x => x, new Comparer())`

Я не особо понял как это сделать, самое близкое до чего я дошел это на ToLookup(что сейчас и реализовано)

2023-06-26 10:33 UTC, ronimizy commented
ладно, тогда давай так оставим пока

2023-06-26 10:34 UTC, ronimizy commented
> > в идеале чтобы она кидалась только на `.ToLookup(x => x, new Comparer())`
> 
> Я не особо понял как это сделать, самое близкое до чего я дошел это на ToLookup(что сейчас и реализовано) Может быть я не на том синтаксисе RegisterSyntaxNodeAction делаю

ну вообще лучше наверное искать `InvocationExpression`

2023-06-26 10:35 UTC, MGSDS commented
> ладно, тогда давай так оставим пока

Кстати, в том что ты вчера смерджил в мастер сломались все анализаторы в SourceKit.Sample

2023-06-26 10:37 UTC, ronimizy commented
по форматированию надо поправить:
1. если блок кода многострочный, то перед и после него должен быть отступ в одну строчку от других блоков кода
2. объявляемые переменные должны быть логически сгруппированы (если они однострочные)
3. если в методе кроме `return` более одной строчки, то он должен быть отделён пропуском строки сверху

2023-06-26 10:39 UTC, ronimizy commented
> > ладно, тогда давай так оставим пока
> 
> Кстати, в том что ты вчера смерджил в мастер сломались все анализаторы в SourceKit.Sample

ну вообще у меня локально работает всё, мб у тебя конфигурация проектов поехала, или кеши почистить надо

2023-06-28 19:32 UTC, ronimizy approved these changes

2023-09-02 12:48 UTC, merged