Feat/nullable disable not allowed
itmo-is-dev/SourceKit pull request #17
Opened 2023-06-25 17:09 UTC by vaner29

2023-06-25 17:12 UTC, vaner29 commented
Ещё у меня почему-то тесты жаловались на конфликт, я в итоге это порешал тем что явно указал референсы на аннотэйшены, но пушить на всякий случай не стал
![image](https://github.com/itmo-is-dev/SourceKit/assets/37649552/bab47d9f-bd0c-4b24-8c2a-faf4f09e7acf)

2023-06-26 07:47 UTC, ronimizy commented
> Ещё у меня почему-то тесты жаловались на конфликт, я в итоге это порешал тем что явно указал референсы на аннотэйшены, но пушить на всякий случай не стал
> ![image](https://user-images.githubusercontent.com/37649552/248573808-bab47d9f-bd0c-4b24-8c2a-faf4f09e7acf.png)

там крч есть сложности потому что к тестам подключается проект с семплом, к семплу подключаются анализаторы, и к тесту тоже, но если семпл в релизе, то они идут через пакет, соответственно для msbuild это разные dll'ки, оттуда и проблема.
я как-нибудь доберусь это решить, но пока чтобы тесты билдились, надо переключать семпл в дебаг

2023-06-26 07:53 UTC, ronimizy requested changes

2023-06-26 07:53 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Nullable/Analyzers/NullableDisableNotAllowedAnalyzer.cs
> +
можешь регать `SyntaxNodeAction` с типом `SyntaxKind.NullableDirectiveTrivia`

2023-06-28 19:38 UTC, xrem approved these changes

2023-09-02 12:47 UTC, merged