IEquatable analyzer
itmo-is-dev/SourceKit pull request #18
Opened 2023-06-25 22:55 UTC by DenChika

2023-06-26 07:45 UTC, ronimizy requested changes
ух, реализация очень не надёжная. не стоит самому определять по синтаксису типы, это умеет делать рослин. 
я бы предложил сразу, как получаешь GenericNameSyntax, перейти к семантическому анализу. GenericNameSyntax соответсвует конкретный TypeSymbol.

плюс тут не решается проблема наследования. напиши такой тест:

```cs
class Base : IEquatable<Base> { ... }

class Derived : Base { ... }

static class Helper
{
    public static Dictionary<Derived, string> Dict { get; } = new();
}
```

2023-06-26 07:45 UTC, ronimizy commented on SourceKit.Sample/Analyzers/Collections/Dictionary/EmptyKeyType.cs
> +}
👀

2023-06-26 07:45 UTC, ronimizy commented on src/SourceKit/Extensions/GenericNameSyntaxExtensions.cs
> +}
очень сомневаюсь в полезности такого экстеншена для общей либы, плюс такой метод кажется ненадёжным, т.к. у `TypeArgumentListSyntax` есть свойство `Arguments` лучше использовать его, а не `ChildNodes`

2023-06-26 07:45 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
> +        var node = context.Node as GenericNameSyntax;
можешь использовать обычный c-cast, сюда другой ноды не придёт

2023-06-26 12:43 UTC, DenChika commented on SourceKit.Sample/Analyzers/Collections/Dictionary/EmptyKeyType.cs
> +}
?)

2023-06-26 12:49 UTC, DenChika commented
> ух, реализация очень не надёжная. не стоит самому определять по синтаксису типы, это умеет делать рослин. я бы предложил сразу, как получаешь GenericNameSyntax, перейти к семантическому анализу. GenericNameSyntax соответсвует конкретный TypeSymbol.
> 
> плюс тут не решается проблема наследования. напиши такой тест:
> 
> ```cs
> class Base : IEquatable<Base> { ... }
> 
> class Derived : Base { ... }
> 
> static class Helper
> {
>     public static Dictionary<Derived, string> Dict { get; } = new();
> }
> ```

![image](https://github.com/itmo-is-dev/SourceKit/assets/79001610/c13733f4-db54-41b4-9a8d-40059806cc74)
- <<не стоит определять по синтаксису типы>>
ты про это?

2023-06-28 18:38 UTC, ronimizy requested changes

2023-06-28 18:38 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
> +        if (keyTypeSymbol is null || keyTypeSymbol.MetadataName == "TKey") return;
`keyTypeSymbol.MetadataName == "TKey"` не понятно зачем 👀

2023-06-28 18:38 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
> +        var keyTypeSymbol = GetFirstTypeSymbolArgument(dictionaryTypeSymbol!);
лучше проверку на null сделай

2023-06-28 18:38 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
> +        var iequatableInterfaces = keyTypeSymbol.FindAssignableTypesConstructedFrom(interfaceNamedType);
`equatableInterfaces`

2023-06-28 18:38 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
> +
```suggestion
        var node = (GenericNameSyntax) context.Node;

        if (node.Identifier.Text != "Dictionary") 
            return;

```

2023-06-28 18:38 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
> +            return;
вынеси кондишен ифа в переменную

2023-06-28 18:38 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
> +    }
как будто это проще заинлайнить в основной метод

2023-06-28 18:38 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
>      }
```suggestion
    private static ISymbol? GetSymbolFromContext(SyntaxNodeAnalysisContext context, SyntaxNode node)
    {
        var model = context.SemanticModel;
        var symbolInfo = model.GetSymbolInfo(node);
        var symbol = symbolInfo.Symbol;

        return symbol;
    }
```

2023-06-29 15:33 UTC, DenChika commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
> +        if (keyTypeSymbol is null || keyTypeSymbol.MetadataName == "TKey") return;
Потому что пустой ключ (OmittedTypeArgument) это не null)

2023-06-29 15:41 UTC, DenChika commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/DictionaryKeyTypeMustImplementEquatableAnalyzer.cs
> +
Ну с переносом return на новую строку согласен, но разделять выражения пустой строкой хз, они же логически связаны

2023-09-02 12:46 UTC, merged