Realise ListForEachNotAllowedAnalyzer and corresponding CodeFixProvider with tests
itmo-is-dev/SourceKit pull request #19
Opened 2023-06-26 12:58 UTC by Bazalii

2023-06-28 18:51 UTC, ronimizy requested changes
склонил локально, для того чтобы работало пришлось делать два изменения:

1. 
<img width="1290" alt="Screenshot 2023-06-28 at 21 51 07" src="https://github.com/itmo-is-dev/SourceKit/assets/71693183/3ddc0b15-fb02-49c4-96e8-5e0f0cd46b2e">
2. поставить проекту `.Collections` release конфигурацию

2023-06-28 18:51 UTC, ronimizy commented on NuGet.config
>          <add key="local-Analyzers.Enumerable" value="src/analyzers/SourceKit.Analyzers.Enumerable/bin/Release"/>
```suggestion
	<add key="local-Analyzers.Collections" value="src/analyzers/SourceKit.Analyzers.Collections/bin/Release"/>
        <add key="local-Analyzers.Enumerable" value="src/analyzers/SourceKit.Analyzers.Enumerable/bin/Release"/>
```

2023-06-28 18:51 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/ListForEachNotAllowedAnalyzer.cs
> +            expressionName.ToString() == "ForEach")
1. вынеси кондишен ифа в переменную
2. иф в целом лучше инвертнуть
3. в основном проекте есть экстеншен для того чтобы по `Type` объекту получить символ типа, используй его для сравнения, а не строку с полным названием (можно сравнить `ConstructedFrom`)

2023-06-28 18:51 UTC, ronimizy commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/ListForEachNotAllowedAnalyzer.cs
> +        }
некорректная проверка, сделай тест на такой случай использования 
в целом можно сразу по операции анализировать, так будет проще 

<img width="650" alt="Screenshot 2023-06-28 at 21 48 28" src="https://github.com/itmo-is-dev/SourceKit/assets/71693183/72952e89-f591-4863-a1d3-5177c90fff48">

2023-06-29 21:31 UTC, Bazalii commented on src/analyzers/SourceKit.Analyzers.Collections/Analyzers/ListForEachNotAllowedAnalyzer.cs
> +            expressionName.ToString() == "ForEach")
Мб всё таки нужно использовать не получение по `Type` объекту символа, а получение символа по полному метадата названию? Условно как-то так: `context.SemanticModel.GetTypeInfo(identifierNameSyntax).Type.OriginalDefinition == context.Compilation.GetTypeByMetadataName("System.Collections.Generic.List'1")`. Ну или же я не понимаю, откуда ты предлагаешь получать непосредственно объект Type..

2023-09-02 12:45 UTC, merged